In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as plt
import json
from collections import Counter
from collections import OrderedDict

In [4]:
# read and format fixtures data
# got fixtures json from the webpage
pd.read_json( 'fixtures.json' )[ 'Data' ].Value
fixtures = pd.json_normalize( pd.read_json( 'fixtures.json' )[ 'Data' ].Value )
fixtures = fixtures[[ 'MatchId', 'HomeTeamShortName', 'AwayTeamShortName' ]]

In [5]:
# default values for nextmatch
fixtures['HomeNextMatch'] = 10
fixtures['AwayNextMatch'] = 10

In [6]:
# populate next match
for i in range(len(fixtures)):
    for team in [ fixtures['HomeTeamShortName'][i], fixtures['AwayTeamShortName'][i] ]:
        for j in range(i+1,len(fixtures)):
            if team == fixtures['HomeTeamShortName'][j] or team == fixtures['AwayTeamShortName'][j]:
                if team == fixtures['HomeTeamShortName'][i]:
                    fixtures.loc[i, ['HomeNextMatch']] = [j - i]
                else:
                    fixtures.loc[i, ['AwayNextMatch']] = [j - i]
                break

In [7]:
# pd options to see full data
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
 
#display(fixtures)

In [13]:
# Get distribution of next match distance

NextArray = list(fixtures['AwayNextMatch'].values) + list( fixtures['HomeNextMatch'].values )
print('total number of matches * 2:', len(NextArray))
count = Counter(NextArray)
count = dict(count)
count = OrderedDict(sorted(count.items()))
count

total number of matches * 2: 148

OrderedDict([(1, 3),
             (2, 1),
             (3, 18),
             (4, 31),
             (5, 31),
             (6, 33),
             (7, 11),
             (8, 5),
             (10, 15)])

In [14]:
# map of number of transfers for each next match distance
# 1 and 10 are bogus so putting 0
transfers = { 1 : 0, 2 : 4, 3 : 4, 4 : 1, 5 : 1, 6: 0, 7 : 0, 8 : 0, 10 : 0 }

In [15]:
# populate populate transfers by match
home_transfers = [ transfers[x] for x in fixtures['HomeNextMatch'].values ]
away_transfers = [ transfers[x] for x in fixtures['AwayNextMatch'].values ]
fixtures[ 'HomeTransfers' ] = home_transfers
fixtures[ 'AwayTransfers' ] = away_transfers
fixtures[ 'TotalTransfers' ] = fixtures[ 'AwayTransfers' ] + fixtures[ 'HomeTransfers' ]

In [16]:
print( 'number of proposed transfers: ', fixtures['TotalTransfers'].sum() )

number of proposed transfers:  138

In [19]:
fixtures.to_csv('proposed_transfers.csv')

In [20]:
fixtures

,MatchId,HomeTeamShortName,AwayTeamShortName,HomeNextMatch,AwayNextMatch,HomeTransfers,AwayTransfers,TotalTransfers
0,219154,GT,CSK,6,5,0,1,1
1,219155,PBKS,KKR,6,7,0,0,0
2,219156,LSG,DC,3,4,4,1,5
3,219157,SRH,RR,6,4,0,1,1
4,219158,RCB,MI,4,7,1,0,1
5,222174,CSK,LSG,6,4,0,1,1
6,222176,DC,GT,4,6,1,0,1
7,222177,RR,PBKS,3,6,4,0,4
8,222178,KKR,RCB,4,6,1,0,1
9,222180,LSG,SRH,5,4,1,1,2
10,222182,RR,DC,6,5,0,1,1
11,222183,MI,CSK,4,5,1,1,2
12,222185,GT,KKR,5,6,1,0,1
13,222186,SRH,PBKS,5,4,1,1,2
14,222187,RCB,LSG,5,6,1,0,1
15,222188,DC,MI,4,6,1,0,1
16,222189,CSK,RR,7,6,0,0,0
17,222190,PBKS,GT,3,5,4,1,5
18,222191,KKR,SRH,3,6,4,0,4
19,222192,RCB,DC,4,8,1,0,1
20,222193,LSG,PBKS,5,6,1,0,1
21,222194,MI,KKR,3,6,4,0,4
22,222195,GT,RR,7,3,0,4,4
23,222196,RCB,CSK,3,5,4,1,5
24,222197,SRH,MI,4,6,1,0,1
25,222198,RR,LSG,6,4,0,1,1
26,222199,PBKS,RCB,4,5,1,1,2
27,222200,DC,KKR,6,5,0,1,1
28,222201,CSK,SRH,4,5,1,1,2
29,222202,LSG,GT,8,5,0,1,1
30,222203,MI,PBKS,4,7,1,0,1
31,222204,RCB,RR,4,5,1,1,2
32,222205,KKR,CSK,3,4,4,1,5
33,222206,SRH,DC,6,6,0,0,0
34,222207,GT,MI,4,7,1,0,1
35,222208,RCB,KKR,7,3,0,4,4
36,222209,RR,CSK,5,4,1,1,2
37,222210,PBKS,LSG,3,5,4,1,5
38,222211,KKR,GT,8,5,0,1,1
39,222212,DC,SRH,4,7,1,0,1
40,222213,CSK,PBKS,5,4,1,1,2
41,222214,MI,RR,3,6,4,0,4
42,222215,LSG,RCB,3,7,4,0,4
43,222216,GT,DC,4,6,1,0,1
44,222217,PBKS,MI,8,4,0,1,1
45,222218,LSG,CSK,5,3,1,4,5
46,222219,SRH,KKR,5,6,1,0,1
47,222220,RR,GT,4,3,1,4,5
48,222221,CSK,MI,6,5,0,1,1
49,222222,DC,RCB,5,4,1,1,2
50,222223,GT,LSG,6,7,0,0,0
51,222224,RR,SRH,4,6,1,0,1
52,222225,KKR,PBKS,3,6,4,0,4
53,222226,MI,RCB,3,6,4,0,4
54,222227,CSK,DC,6,4,0,1,1
55,222228,KKR,RR,5,4,1,1,2
56,222229,MI,GT,6,5,0,1,1
57,222230,SRH,LSG,4,5,1,1,2
58,222231,DC,PBKS,5,5,1,1,2
59,222232,RR,RCB,6,5,0,1,1
60,222233,CSK,KKR,6,7,0,0,0
61,222234,GT,SRH,8,3,0,4,4
62,222235,LSG,MI,5,6,1,0,1
63,222236,PBKS,DC,2,3,4,4,8
64,222237,SRH,RCB,4,5,1,1,2
65,222238,PBKS,RR,10,10,0,0,0
66,222239,DC,CSK,10,10,0,0,0
67,222240,KKR,LSG,10,10,0,0,0
68,222241,MI,SRH,10,10,0,0,0
69,222242,RCB,GT,10,10,0,0,0
70,222243,TBC,TBC,1,10,0,0,0
71,222244,TBC,TBC,1,10,0,0,0
72,222245,TBC,TBC,1,10,0,0,0
73,222246,TBC,TBC,10,10,0,0,0